### ISSUE TITLE
Incorrect log-likelihood displayed?

### ISSUE THREAD

**Issue by jamesnordlund** [JohannesSKunz/brglm#1]
https://github.com/JohannesSKunz/brglm/blob/8fd546f823157e395ba86f95763863efb642ba5f/brglm.ado#L127

Should this line be replaced with:
```
di as text  "Log-likelihood: " as result `ll'        // Display log-likelihood
```

As is, the value in `e(ll)` that prints to the screen comes from the WLS line:
https://github.com/JohannesSKunz/brglm/blob/8fd546f823157e395ba86f95763863efb642ba5f/brglm.ado#L87

rather than the post-convergence log-likelihood calculated later on in the ado file.

For instance, in the example code:
```
clear *
set matsize 11000
webuse union
brglm union age grade i.not_smsa south if year==88 , model(probit)
ereturn list
```
The printed log-likelihood is -4243.8314 but the value stored in `e(ll)` is -1264.869557941735.  The suggested change would have the printout display -1264.869557941735.

**Comment by JohannesSKunz** [comment]
That is entirely correct. I have corrected the mistake, in the now available version v1.0.1.
Thank you, James!
